### ISSUE TITLE
Incorrect Lines

### ISSUE THREAD

**Issue by sercoin** [woodbri/osrm-tools#2] opened 2014-02-06 11:14 UTC
Hi,

I extract and prepare my own data. After routed I got this incorrect lines. This is not normal. Is there any reason to be like this or did I something wrong?

![screen](https://f.cloud.github.com/assets/5477273/2097767/5dd4eb9e-8f1f-11e3-9016-3b970ed2ddb2.png)

**Comment by woodbri** [comment] 2014-02-06 14:31
It appears OSRM simplifies the lines. I request the out from OSRM at z=18 which I think is the highest zoom level supported based on:
https://github.com/DennisOSRM/Project-OSRM/wiki/Server-api#wiki-additional-parameters
Anyway the data that I return is what I get from OSRM.

**Comment by sercoin** [comment] 2014-02-06 14:41
```
    "select case when dir_travel='T' then target "
    "            else source end as source, "
    "       case when dir_travel='T' then source "
    "            else target end as target, "
    "       st_length_spheroid(st_geometryn(the_geom, 1), "
    "           'SPHEROID[\"GRS_1980\",6378137,298.257222101]'::spheroid"
    "           )::integer as length, "
    "       case when dir_travel = 'B' then 0 else 1 end::integer as dir, "
    "       round(case when speed_cat='1' then 130.0 "
    "                  when speed_cat='2' then 101.0 "
    "                  when speed_cat='3' then  91.0 "
    "                  when speed_cat='4' then  71.0 "
    "                  when speed_cat='5' then  51.0 "
    "                  when speed_cat='6' then  31.0 "
    "                  when speed_cat='7' then  11.0 "
    "                  when speed_cat='8' then   5.0 "
    "                  else 1.0 "
    "                  end * "
    "           st_length_spheroid(st_geometryn(the_geom, 1), "
    "             'SPHEROID[\"GRS_1980\",6378137,298.257222101]'::spheroid"
    "           ) * 0.027777778)::integer as weight, "
    "       speed_cat::integer as rank, "
    "       case when b.id is null then 0 else b.id end::integer as nameid, "
    "       case when roundabout='Y' then 1 "
    "            else 0 end::integer as roundabout, "
    "       case when tunnel='Y' or bridge='Y' then 1 "
    "            else 0 end::integer as ignoreingrid, "
    "       0::integer as accessrestricted "
    "  from " + etable + " a left outer join " + etable + "_osrm_names b "
    "    on a.name=b.name where source != target "
    " order by a.target asc " + LIMIT,
    "edges",
```

In addition,

case when dir_travel='T' then target else source end as source, 
case when dir_travel='T' then source else target end as target, 

What is this lines doing?

**Comment by sercoin** [comment] 2014-02-06 14:46
GET
/viaroute?output=json&jsonp=OSRM.JSONP.callbacks.route&instructions=true&z=18&loc=41.34494,19.80364&loc=41.34327,19.8081
HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.95 Safari/537.36
Accept: text/javascript, text/html, application/xml, text/xml, _/_
Accept-Encoding: *
Accept-Language: tr-tr,tr;q=0.8,en-us;q=0.5,en;q=0.3
Host: 192.168.1.48:5005
Connection: Keep-Alive

HTTP/1.0 200 OK
Content-Length: 987
Content-Type: text/javascript
Content-Disposition: attachment; filename="route.js"

OSRM.JSONP.callbacks.route({"version": 0.3,"status":0,"status_message": 
"Found route between points","route_geometry": 
"yznzmAu_vwd@hKiJbBwBfTwQbBwBvL{JvQ{OjCk}A~RoUvQsN~MgJsI{Y{EoPqGuU","route_instructions": 
[["10","uRruga BesaSh6Sh81Sh34Nava",156,0,5,"156m","SE",145],["8","ga
Nexhat HakiuRruga Ibrahi",242,6,8,"242m","E",94],["7","ani
Kryeziu",100,10,3,"100m","NE",62],["15","",0,13,0,"","N",0.0]],"route_summary":{"total_distance":500,"total_time":31,"start_point":"uRruga
BesaSh6Sh81Sh34Nava","end_point":"ani
Kryeziu"},"alternative_geometries": 
[],"alternative_instructions":[],"alternative_summaries":[],"route_name":["uRruga
BesaSh6Sh81Sh34Nava","ga Nexhat HakiuRruga
Ibrahi"],"alternative_names":[["",""]],"via_points":[[41.344957,19.803659 ],[41.343287,19.808093
]],"hint_data": {"checksum":-1015138978, "locations": 
["1_EAAHkFAAAWAAAAOgAAAMkwS4I0CtI_vd92AgsuLgE",
"O7kBANgGAAAdAAAAEQAAABfiT13aAeQ_N9l2Al0_LgE"]},"transactionId": "OSRM Routing Engine JSON Descriptor (v0.3)"})

This is my request and response. We already request in z=18.

**Comment by woodbri** [comment] 2014-02-06 14:52
`dir_travel` can have values of `null|T|F|B` where `T` is to->from, `F` is from->to , and other values are both ways. This indicates onewayness and the direction that is allowed. If the edge is oneway reversed then I flip the the start and end nodes so the direction of travel is from->to.

**Comment by sercoin** [comment] 2014-02-06 15:08
But 2 condition goes to same result.

case when dir_travel='T' then target else source end as source, 
case when dir_travel='T' then source else target end as target,

one of the request should be 'F' I think.

**Comment by woodbri** [comment] 2014-02-06 15:12
Yeah, it is confusing, when I looked at it the other day I thought I had a typo and had to work it out on paper. It is correct.

**Comment by woodbri** [comment] 2014-02-06 15:13
regarding the z=18: the api doc is not clear, and it occurs to me that totally leaving off the `&z=18` might give a better result. Given it a try and let me know.

**Comment by sercoin** [comment] 2014-02-06 15:23
When will you commit the changed pgr2osrm?

I try with &z=18 and without &z=18 but both response are same.

**Comment by woodbri** [comment] 2014-02-06 15:46
I have no changes to commit. The route is coming from OSRM not pgr2osrm. It occurs to me that I might be able to explode the linestring into multiple little edges and assign node_ids to all the segments, but this would greatly increase the problem size and the transfer data file sizes, so I'm not inclined to do that. It would also mean that all of the logic would need to change for how node_ids are assigned.

**Comment by woodbri** [comment] 2014-02-06 21:00
I get similar routes with my data. I think osrm-extract explodes a polyline into multiple edges connected end to end but pgrouting uses the polyline as the edge. I might look at this later but I don't have the time now. I asked on OSRM IRC channel about the z=18 but did not get a response. Dennis is on vaction  for a week.

If you want to try exploding the linestring into multiple edges in pgrouting/postgis and then create a topology on that, you can try exporting that and I suspect you will get better results. When Dennis is back I will discuss it with him and get his thoughts on it.

**Comment by sercoin** [comment] 2014-02-06 21:13
Thanks for you reply. I'm waiting your solution. I hope it will solve soon. :)

**Comment by sercoin** [comment] 2014-02-12 14:56
Is there any update for this issue?

**Comment by woodbri** [comment] 2014-02-12 15:19
Please do not wait on a fix on this. A pull request would be considered if you want to try it. I explained a work-around to this is to explode the edges into line segments in postgis. I would create a temp table explode the edges into that then export the temp table to OSRM. This could be slow for a large table.

**Comment by woodbri** [comment] 2014-02-12 15:33
Another approach would be to extract the data from postgres and explode and renumber the edges and nodes in C++ then write the normalized file format. Either way this is a major rewrite of all the code and not a trivial fix.

**Comment by sercoin** [comment] 2014-02-13 13:03
![screens](https://f.cloud.github.com/assets/5477273/2159793/b73f47b4-94ac-11e3-83b9-e3679157ee51.png)

1st and 2nd pictures are belongs to http://map.project-osrm.org/ . And there is only 500 metre distance between 2 end points.

3rd and 4rd pictures are belongs to my project. Start and end points are same places. There are no restrictions and road directions defined. And my profile like that;

default_speed = 1

speed_profile = {
  ["motorway"] = default_speed,
  ["motorway_link"] = default_speed,
  ["trunk"] = default_speed,
  ["trunk_link"] = default_speed,
  ["primary"] = default_speed,
  ["primary_link"] = default_speed,
  ["secondary"] = default_speed,
  ["secondary_link"] = default_speed,
  ["tertiary"] = default_speed,
  ["tertiary_link"] = default_speed,
  ["unclassified"] = default_speed,
  ["residential"] = default_speed,
  ["living_street"] = default_speed,
  ["service"] = default_speed,
--  ["track"] = 5,
  ["ferry"] = default_speed,
  ["shuttle_train"] = default_speed,
  ["default"] = default_speed
}

take_minimum_of_speeds  = false
obey_oneway             = true
obey_bollards           = true
use_restrictions        = true
ignore_areas        = true -- future feature
traffic_signal_penalty  = 2
u_turn_penalty          = 20

When I used this profile on planet.osm data the route was same with 1st and 2nd pictures. In the 3rd and 4rd pictures 500 metre distance changes the route complately. 

The data informations of roads like that;
![data](https://f.cloud.github.com/assets/5477273/2159859/42ba7128-94ae-11e3-8f73-99fae4ef9fbc.PNG)

Is there any mistake on profile or data? What can cause this error?

**Comment by woodbri** [comment] 2014-02-13 14:11
Are you using the most recent code base? to a git pull can recompile and process your data, because I fixed the computation of the weights that I passed to OSRM that was causing similar behavior.

Can you route from 3 to a point just north of 1?

**Comment by sercoin** [comment] 2014-02-13 15:10
There is no difference between the route sides like below,
![screens2](https://f.cloud.github.com/assets/5477273/2160951/681624f0-94c0-11e3-9f79-cbd59f4754e1.png)

I only move north point 1 mm northern on map and the route changes like that;
![screens3](https://f.cloud.github.com/assets/5477273/2160980/e63f167a-94c0-11e3-8d76-ee09885c89f2.png)

**Comment by woodbri** [comment] 2014-02-13 15:19
ok, thanks. just checking for broken topology. but it looks ok. make sure you are using the latest code from github.

```
[master] ~/work/osrm-tools$ git describe --tags --long
v1.1.0-0-gf0af0c8
```

**Comment by sercoin** [comment] 2014-02-14 08:45
I cloned and build latest code and now I get 

[warn] .restrictions was prepared with different build.
Reprocess to get rid of this warning.

error. I try to prepared with 4 different Project-OSRM release. One of that releases is latest code. Which release of Project-OSRM fits with pgr2osrm?

**Comment by woodbri** [comment] 2014-02-14 14:15
It currently only works with the OSRM master branch. When the next release is done I will update it to work with that.

```
[master] ~/work/Project-OSRM$ git describe --tags --long
v0.3.7-2-gfbbd6ca
```

OK, looks like master has has been updated since then and is now at:

```
[master] ~/work/Project-OSRM$ git describe --tags --long
v0.3.7-4-gcd6075a
```

so I'll need to do another update. In meanwhile you should be able to do this:

```
git checkout -b osrm-tools v0.3.7-2-gfbbd6ca
```

and then build osrm-tools against that source tree.
I'll add a note to my wiki page to help users.

**Comment by sercoin** [comment] 2014-02-14 15:57
I use latest code like you said and the wrong route which we talk before is correct now like below;
![correct](https://f.cloud.github.com/assets/5477273/2172235/63e408fe-9590-11e3-81a7-ae0b50350a70.PNG)

But now there is another wrong route show up. You can see below;
![screens5](https://f.cloud.github.com/assets/5477273/2172246/83867700-9590-11e3-9dec-a517208b7ddc.png)

And the data informations like this;
![datas2](https://f.cloud.github.com/assets/5477273/2172253/912bbb04-9590-11e3-9c40-b5a55240a6db.png)

It is not complately solved yet.

**Comment by woodbri** [comment] 2014-02-14 16:35
Can you create a dump of the pgrouting table using a bbox a little larger than your route end points. Something like:

```
pgsql2shp -f edges.shp -h localhost -u user -g the_geom dbname "select * from albania where the_geom && st_expand(st_setsrid('LINESTRING(p1x p1y,p2x p2y)'::geometry, 4326), 0.001)"
```

This assumes you are using epsg:4326.

Do the same for the vertices_tmp table and zip up the shapefiles for both and send them to me. Then I can load this up and test it and also debug the problem working with a small dataset. Thanks.

**Comment by sercoin** [comment] 2014-02-15 12:29
Hi,

As you request I sent you the shapes.

Thanks

**Comment by woodbri** [comment] 2014-02-15 15:02
First look at your data and a few problems I am noticing are that the `len_m` is not the length in meters. This appears to be computed using `st_length(the_geom)` which return the length in the_geom units in this case degrees in epsg:4326. You should compute this with `ST_Length_Spheroid(the_geom, 'SPHEROID["GRS_1980",6378137,298.257222101]')` which return the length in meters. the cost value seems to be the cost based on your `len_m` values factoring the speed_cat to compute the number of 1/10 sec intervals to traverse the edge at your `speed_cat`.

Also I will note that your `id` column is double precision and OSRM expects UINT32, so if you values exceed that you will have bed data. I do not check for errors of this kind.

The len_m is ignored and I calculate the correct length in pgr2osrm so that should not effect the results.

**Comment by woodbri** [comment] 2014-02-15 15:51
@sercoin can you post the lat,lon for the two points on the last route that gave you a problem so I can run that with the data you sent.

**Comment by sercoin** [comment] 2014-02-16 13:21
Hi,

Start point lat: 41.325900 lon:19.803466

End point lat: 41.321442 lon: 19.805324

**Comment by woodbri** [comment] 2014-02-16 14:13
I am getting the osrm response below. I'll have to set up app to visualize this, but it does not seem to be taking a straight line route.

```
 select * from osrm_viaroute(array[41.325900,41.321442], array[19.803466,19.805324], true, true);
{"version": 0.3,
 "status":0,
 "status_message": "Found route between points",
 "route_geometry": "{riymAuquwd@zFmB~RcGbGzYvLrl@vLrg@vVgOrDgEzY_b@~Wwe@zTw`@vB_Dve@o_@gEgTnAg@fOoFfO{ErScGrI_D|FsB",
 "route_instructions": [
  ["10","Rruga Muhamet Gjollesha",51,0,3,"51m","S",162],
  ["3","",38,2,4,"38m","W",248],
  ["1","",65,3,7,"65m","W",248],
  ["1","",59,4,6,"59m","SW",246],
  ["7","",47,5,5,"47m","SE",153],
  ["1","",13,6,1,"13m","SE",140],
  ["1","",66,7,7,"66m","SE",136],
  ["1","",68,8,7,"68m","SE",131],
  ["1","",59,9,6,"59m","SE",131],
  ["1","",9,10,1,"9m","SE",135],
  ["1","",81,11,9,"81m","SE",148],
  ["7","",30,12,3,"30m","E",69],
  ["3","Rruga Muhamet Gjollesha",103,13,12,"103m","S",159],
  ["1","",34,17,2,"34m","S",161],
  ["15","",0,19,0,"","N",0.0]],
 "route_summary":{
  "total_distance":732,
  "total_time":86,
  "start_point":"Rruga Muhamet Gjollesha",
  "end_point":""},
 "alternative_geometries": [],
 "alternative_instructions":[],
 "alternative_summaries":[],
 "route_name":["","Rruga Muhamet Gjollesha"],
 "alternative_names":[["",""]],
 "via_points":[
  [41.325886,19.803435 ],
  [41.321453,19.805348 ]],
 "hint_data": {
  "checksum":-1649968959, 
  "locations": ["mRsAAJUBAAARAAAAFAAAAKwl_SW52dw_PpV2AistLgE",
    "CwkAAAAAAAASAAAAEQAAAFpNu7kMY-A_7YN2AqQ0LgE"]},
 "transactionId": "OSRM Routing Engine JSON Descriptor (v0.3)"}
```

**Comment by sercoin** [comment] 2014-02-16 15:34
Btw I changed the <code>id</code> column to integer and recalculate the <code>len_m</code> and <code>cost</code> columns. But the result is same just like you said.

**Comment by woodbri** [comment] 2014-02-16 16:47
Yeah, if you look at pgr2osrm.cpp you will see that I have SQL the computes the values correctly. You can also see the raw SQL listed in https://github.com/woodbri/osrm-tools/tree/master/pgr2osrm/README.md. if you run that SQL it is basically the records that get formatted into the files passed to osrm-prepare.

The path that I got does not look like your path (just looking at the json output above because it has 15 instructions. I'll try to setup a viewer app so I can see what the route looks like.

**Comment by sercoin** [comment] 2014-02-19 09:16
Is there any update?

**Comment by woodbri** [comment] 2014-02-22 19:19
This is not a bug. It is an issue with your data. osrm-tools and Project-OSRM appear to be doing the correct things and return the correct results. Here is my analysis. Looking at the image below the route is highlighted in purple. Your complaint is why did it not follow the straight line path.

![osrm-tools-issue2-1](https://f.cloud.github.com/assets/805250/2238545/bc13accc-9bf4-11e3-95a2-973c86fd0850.png)

I'm only comparing the two divergent paths (ie: ignoring the segments that are common to both). Here it the path that was returned:

```
bug1=# select gid, id, speed_cat, dir_travel, bridge, tunnel, roundabout, source, target, len_m, cost,
(round(st_length_spheroid(st_geometryn(the_geom, 1),
      'SPHEROID["GRS_1980",6378137,298.257222101]'::spheroid
    ) / case when speed_cat='1' then 130.0
           when speed_cat='2' then 101.0
           when speed_cat='3' then  91.0
           when speed_cat='4' then  71.0
           when speed_cat='5' then  51.0
           when speed_cat='6' then  31.0
           when speed_cat='7' then  11.0
           when speed_cat='8' then   5.0
           else 1.0
           end * 36.0)::integer) as weight
from example where gid in (5803,6891,6890,342,3198,3116,2640,1579,412,5674,5673);
 gid  |    id     | speed_cat | dir_travel | bridge | tunnel | roundabout | source | target |         len_m         |          cost          | weight
------+-----------+-----------+------------+--------+--------+------------+--------+--------+-----------------------+------------------------+--------
  342 | 912303761 | 6         | B          | N      | N      | N          |  16716 |  39548 |  0.000460434577329169 |  0.0000148527283009409 |     55
  412 | 912304734 | 6         | B          | N      | N      | N          |  49770 |  20420 | 0.0000999999999990564 | 0.00000322580645158246 |     11
 1579 | 912329236 | 6         | B          | N      | N      | N          |  20420 |  30545 |   0.00064350602172717 |  0.0000207582587653926 |     69
 2640 | 912348825 | 6         | B          | N      | N      | N          |  30545 |  30546 |  0.000738243357691531 |  0.0000238143018610171 |     79
 3116 | 912356674 | 6         | B          | N      | N      | N          |  30546 |  33965 |   0.00071049131578255 |  0.0000229190747026629 |     78
 3198 | 912357937 | 6         | B          | N      | N      | N          |  33965 |  16716 |  0.000134536240470661 | 0.00000433987872486004 |     15
 5673 | 987612578 | 6         | B          | N      | N      | N          |  72899 |  40697 |  0.000354449948773665 |  0.0000114338693152795 |     35
 5674 | 987612579 | 6         | B          | N      | N      | N          |  72899 |  49770 |  0.000825321706399537 |   0.000026623280851598 |     96
 5803 | 987629588 | 6         | B          | N      | N      | N          |  16101 |  19204 |  0.000449221548901948 |  0.0000144910177065145 |     45
 6890 | 990654004 | 6         | B          | N      | N      | N          |  39548 |  16100 |  0.000686221538574044 |  0.0000221361786636788 |     69
 6891 | 990654005 | 6         | B          | N      | N      | N          |  16100 |  16101 |  0.000762430324685875 |  0.0000245945266027702 |     76
(11 rows)
bug1=# select sum(round(st_length_spheroid(st_geometryn(the_geom, 1),                 'SPHEROID["GRS_1980",6378137,298.257222101]'::spheroid
    ) / case when speed_cat='1' then 130.0
           when speed_cat='2' then 101.0
           when speed_cat='3' then  91.0
           when speed_cat='4' then  71.0
           when speed_cat='5' then  51.0
           when speed_cat='6' then  31.0
           when speed_cat='7' then  11.0
           when speed_cat='8' then   5.0
           else 1.0
           end * 36.0)::integer) as weight
from example where gid in (5803,6891,6890,342,3198,3116,2640,1579,412,5674,5673);
 weight
--------
    628
(1 row)
```

here is the straight line path:

```
bug1=# select gid, id, speed_cat, dir_travel, bridge, tunnel, roundabout, source, target, len_m, cost,
(round(st_length_spheroid(st_geometryn(the_geom, 1),
      'SPHEROID["GRS_1980",6378137,298.257222101]'::spheroid
    ) / case when speed_cat='1' then 130.0
           when speed_cat='2' then 101.0
           when speed_cat='3' then  91.0
           when speed_cat='4' then  71.0
           when speed_cat='5' then  51.0
           when speed_cat='6' then  31.0
           when speed_cat='7' then  11.0
           when speed_cat='8' then   5.0
           else 1.0
           end * 36.0)::integer) as weight
from example where gid in (1318,3013,6834,6833,3120,1644);
 gid  |    id     | speed_cat | dir_travel | bridge | tunnel | roundabout | source | target |        len_m         |          cost          | weight
------+-----------+-----------+------------+--------+--------+------------+--------+--------+----------------------+------------------------+--------
 1318 | 912325225 | 6         | B          | N      | N      | N          |  19203 |  19204 | 0.000120830459736076 | 0.00000389775676567986 |     15
 1644 | 912330344 | 6         | B          | N      | N      | N          |  40697 |  33993 | 0.000891571646023967 |  0.0000287603756781925 |    111
 3013 | 912355352 | 7         | B          | N      | N      | N          |  33387 |  19203 | 0.000555427763078051 |  0.0000504934330070955 |    195
 3120 | 912356736 | 6         | B          | N      | N      | N          |  33993 |  33994 | 0.000456946386356927 |  0.0000147402060115138 |     57
 6833 | 990095273 | 6         | B          | N      | N      | N          |  33994 |  70651 | 0.000349284983927594 |  0.0000112672575460514 |     43
 6834 | 990095274 | 7         | B          | N      | N      | N          |  70651 |  33387 | 0.000676239602512581 |  0.0000614763275011437 |    237
(6 rows)

bug1=# select sum(round(st_length_spheroid(st_geometryn(the_geom, 1),                 'SPHEROID["GRS_1980",6378137,298.257222101]'::spheroid
    ) / case when speed_cat='1' then 130.0
           when speed_cat='2' then 101.0
           when speed_cat='3' then  91.0
           when speed_cat='4' then  71.0
           when speed_cat='5' then  51.0
           when speed_cat='6' then  31.0
           when speed_cat='7' then  11.0
           when speed_cat='8' then   5.0
           else 1.0
           end * 36.0)::integer) as weight
from example where gid in (1318,3013,6834,6833,3120,1644);
 weight
--------
    658
(1 row)
```

As you can see the cost to follow the straight line path is 658 and the routed path is 628 which costs less.

The reason is probably that some of the edges on the straight path have the speed_cat=7 which is approximately 3 time slower than speed_cat=6.

Closing.

**Closed as completed by woodbri** 2014-02-22 19:19 UTC

**Comment by woodbri** [comment] 2014-02-22 19:25
Here is the map you can zoom in. Labels are based on my databases gid values.
http://imaptools.com:8080/demo/bug1.html
